@baseUrl = http://localhost:3000

# @name auth
GET http://localhost:3000/dev/token

### [auth] Create Payout Instruction
# @name collectionsCreated
POST http://localhost:3000/collections/create
Authorization: Bearer {{auth.response.body.token}}
Content-Type: application/json

{
    "corpId": "DSGRFB",
    "currencyIsoCode": "AUD",
    "amount": 100,
    "countryCode": "AU",
    "type": "local"
}

### [auth] Create Payout Instruction
# @name collectionsRates
PUT http://localhost:3000/collections/rates
Authorization: Bearer {{auth.response.body.token}}
Content-Type: application/json

{
    "_id": "{{collectionsCreated.response.body._id}}"
}