import { string, number, boolean, date, object, mixed } from "yup";

export const revenueSchema = object().shape({
  fxRevenue: string(),
  fxRevenueStatus: string(),
  fxRevenueUSD: string(),
  gatewayFee: number(),
  gatewayFeeCurrency: string(),
  gatewayFeeMatchedTier: string(),
  gatewayFeePercent: number(),
  gatewayFeeStatic: number(),
  gatewayFeeStatus: string(),
  gatewayFeeTier: string(),
  gatewayFeeUSD: number(),
  gatewayId: string(),
  gatewayName: string(),
  payinDebit: number().required("payinDebit is required"),
  payinDebitTotal: number(),
  payinFee: number(),
  payinFeeCurrency: string(),
  payinIncrementAmount: number(),
  payinMaxAmount: number(),
  payinMinAmount: number(),
  payinPartner: string().required("payinPartner is required"),
  payinSpread: string(),
  payoutPartner: string().required("payoutPartner is required"),
  fundCurrencyRate: number(),
  fundUSD: string(),
  payoutCurrencyRate: number(),
  payoutFee: number(),
  payoutFeeCurrency: string(),
  payoutDebit: number(),
  payoutDebitTotal: number(),
  payoutUSD: number(),
  profit: number(),
  revenueIds: string(),
  ticketRevenue: number(),
  ticketRevenueCurrency: string(),
  ticketRevenueMatchedTier: string(),
  ticketRevenueStatus: string(),
  ticketRevenueUSD: number(),
});

export const statementSchema = object().shape({
  otherId: string(),
  refundId: string(),
  statementId: string(),
  statementNotifyManualFailedId: string(),
  statementNotifyManualRefundedId: string(),
  statementTicketFeeId: string(),
});
